/*
@license

dhtmlxGantt v.4.1.0 Professional Evaluation
This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t.config.smart_rendering=!0,t._smart_render={getViewPort:function(){var e=this.getScrollSizes(),i=t._restore_scroll_state();return i.y=Math.min(e.y_inner-e.y,i.y),{y:i.y,y_end:i.y+e.y}},getScrollSizes:function(){var e=t._scroll_sizes();return e.x=e.x||0,e.y=e.y||t._order.length*t.config.row_height,e},isInViewPort:function(t,e){return!!(t.y<e.y_end&&t.y_end>e.y)},isTaskDisplayed:function(t){return this.isInViewPort(this.getTaskPosition(t),this.getViewPort())},isLinkDisplayed:function(t){
return this.isInViewPort(this.getLinkPosition(t),this.getViewPort())},getTaskPosition:function(e){var i=t.getTaskTop(e);return{y:i,y_end:i+t.config.row_height}},getLinkPosition:function(e){var i=t.getLink(e),n=t.getTaskTop(i.source),a=t.getTaskTop(i.target);return{y:Math.min(n,a),y_end:Math.max(n,a)+t.config.row_height}},getRange:function(e){e=e||0;var i=this.getViewPort(),n=Math.floor(Math.max(0,i.y)/t.config.row_height)-e,a=Math.ceil(Math.max(0,i.y_end)/t.config.row_height)+e,r=t._order.slice(n,a);
return r},_redrawItems:function(t,e){for(var i in t){var n=t[i];for(var i in n.rendered)n.hide(i);for(var a=0;a<e.length;a++)n.restore(e[a])}},_getVisibleTasks:function(){return t._get_tasks_data()},_getVisibleLinks:function(){for(var e=[],i=t._get_links_data(),n=0;n<i.length;n++)this.isLinkDisplayed(i[n].id)&&e.push(i[n]);return e},_recalculateLinkedProjects:function(e){for(var i={},n=0;n<e.length;n++)i[e[n].source]=!0,i[e[n].target]=!0;for(var n in i)t.isTaskExists(n)&&t.resetProjectDates(t.getTask(n));
},updateRender:function(){t.callEvent("onBeforeSmartRender",[]);var e=this._getVisibleLinks();this._recalculateLinkedProjects(e),this._redrawItems(t._get_task_renderers(),this._getVisibleTasks()),this._redrawItems(t._get_link_renderers(),e),t.callEvent("onSmartRender",[])},cached:{},_takeFromCache:function(t,e,i){this.cached[i]||(this.cached[i]=null);var n=this.cached[i];return void 0!==t?(n||(n=this.cached[i]={}),void 0===n[t]&&(n[t]=e(t)),n[t]):(n||(n=e()),n)},initCache:function(){for(var e=["getLinkPosition","getTaskPosition","isTaskDisplayed","isLinkDisplayed","getViewPort","getScrollSizes"],i=0;i<e.length;i++){
var n=e[i],a=t.bind(this[n],this);this[n]=function(t,e){return function(i){return this._takeFromCache(i,t,e)}}(a,n)}this.invalidateCache(),this.initCache=function(){}},invalidateCache:function(){function e(){s.cached.getViewPort=null,s.cached.getScrollSizes=null,s.cached.isTaskDisplayed=null,s.cached.isLinkDisplayed=null}function i(){s.cached.isTaskDisplayed=null,s.cached.isLinkDisplayed=null,s.cached.getLinkPosition=null,s.cached.getTaskPosition=null}function n(){e(),i()}function a(t){s.cached.isTaskDisplayed&&(s.cached.isTaskDisplayed[t]=void 0),
s.cached.getTaskPosition&&(s.cached.getTaskPosition[t]=void 0)}function r(t){s.cached.isLinkDisplayed&&(s.cached.isLinkDisplayed[t]=void 0),s.cached.getLinkPosition&&(s.cached.getLinkPosition[t]=void 0)}var s=this;t.attachEvent("onClear",function(){n()}),t.attachEvent("onParse",function(){n()}),t.attachEvent("onAfterLinkUpdate",r),t.attachEvent("onAfterTaskAdd",n),t.attachEvent("onAfterTaskDelete",n),t.attachEvent("onAfterTaskUpdate",a),t.attachEvent("onGanttScroll",e),t.attachEvent("onDataRender",n),
this.invalidateCache=function(){}}},t._smart_render.initCache(),t.attachEvent("onGanttScroll",function(e,i,n,a){if(t.config.smart_rendering){i!=a&&t._smart_render.updateRender();var r=Math.floor(a/t.config.row_height)*t.config.row_height;t.$grid_data.scrollTop=a-r}}),t.attachEvent("onDataRender",function(){t.config.smart_rendering&&t._smart_render.updateRender()}),function(){function e(e,i){return function(){return t.config.smart_rendering?i.apply(this,arguments):e.apply(this,arguments)}}var i=t._get_task_filters;
t._get_task_filters=e(t._get_task_filters,function(){var e=i.call(t);return e.push(function(e){return t.config.smart_rendering?t._smart_render.isTaskDisplayed(e):!0}),e});var n=t._get_link_filters;t._get_link_filters=e(t._get_link_filters,function(){var e=n.call(t);return e.push(function(e){return t.config.smart_rendering?t._smart_render.isLinkDisplayed(e):!0}),e}),t._get_data_range=e(t._get_data_range,function(){return this._smart_render.getRange()})}()});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_smart_rendering.js.map